### ISSUE TITLE
Can't see buttons in product page

### ISSUE THREAD

**Issue by giacmir** [Adyen/adyen-magento2-express-checkout#40]
**Describe the bug**
Buttons are not appearing in product page, I get this error in console:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'configuration')
    at UiClass.getGooglePayConfig (button.js:258:64)
    at UiClass.initialiseGooglePayComponent (button.js:173:46)
```
This seem to happen because `button.js` is trying to access `gatewayMerchantId: googlePaymentMethod.configuration.gatewayMerchantId` while `googlePaymentMethod` being `null`.

If I'm correct this `googlePaymentMethod` variable is populated in `getPaymentMethod.js` at line 9 by calling
`customerData.get('adyen-express-pdp');`

but `\Adyen\ExpressCheckout\CustomerData\AdyenExpress` always returns an empty array.

How can this even work? 

**To Reproduce**
1. Install and configure Adyen module
2. Install and configure this module
3. navigate to a product page

**Expected behavior**
Fast checkout buttons should be visible

**Desktop (please complete the following information):**
 - OS: ubuntu GNU/Linux
 - Browser chrome
 - Version 116.0.5845.96

**Comment by candemiralp** [comment]
Hello @giacmir,

Thank you for raising this issue. Could you please verify that you've configured Google Pay payment method in your Adyen Customer Area with `googlepay` variant for the desired currency and countries?

Best Regards,
Can

**Comment by candemiralp** [comment]
Closing this issue as it's not reproducible on versions V2 and V3.
