### ISSUE TITLE
[ECP-9158] Checkout not working with required agreements 

### ISSUE THREAD

**Issue by dimitriBouteille** [Adyen/adyen-magento2-express-checkout#66]
**Describe the bug**

When I try place order with Apple Pay, I have the following error :

> The order wasn't placed. First, agree to the terms and conditions, then try placing your order again.

**To Reproduce**

- Create required agreements in Magento
- Try place order with Apple Pay (maybe same error with Google Pay)
- See error on request `/payment-information`
- :boom: 

**Expected behavior**

Agreements validation must be disabled with express checkout.

**Error trace**

```json
{
    "message": "Die Bestellung wurde noch nicht platziert. Bitte stimmen Sie erst unseren Nutzungsbedingungen zu und versuchen Sie dann die Bestellung erneut abzusenden.",
    "trace": "#0 /vendor/magento/module-checkout-agreements/Model/Checkout/Plugin/GuestValidation.php(80): Magento\\CheckoutAgreements\\Model\\Checkout\\Plugin\\GuestValidation->validateAgreements()\n#1 /vendor/magento/framework/Interception/Interceptor.php(121): Magento\\CheckoutAgreements\\Model\\Checkout\\Plugin\\GuestValidation->beforeSavePaymentInformationAndPlaceOrder()\n#2 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#3 /generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(23): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callPlugins()\n#4 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder()\n#5 /vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()\n#6 /vendor/magento/module-webapi/Controller/Rest.php(195): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process()\n#7 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch()\n#8 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent()\n#9 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#10 /generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins()\n#11 /vendor/magento/framework/App/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch()\n#12 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Framework\\App\\Http->launch()\n#13 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Framework\\App\\Http\\Interceptor->___callParent()\n#14 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Framework\\App\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#15 /generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\\Framework\\App\\Http\\Interceptor->___callPlugins()\n#16 /vendor/magento/framework/App/Bootstrap.php(264): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#17 /pub/index.php(30): Magento\\Framework\\App\\Bootstrap->run()\n#18 {main}"
}
```

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

Thank you for raising this issue. We have created an internal ticket to solve this one.

Best regards,
Can

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

We have created a PR to fix the issue on Apple Pay. We didn't observe any issue on Google Pay and it works as expected with agreements.

Best Regards,
Can

**Comment by dimitriBouteille** [comment]
Hi @candemiralp 

I just updated the module to 2.4.1 and the bug is still present :( When I look at the code, I see that the agreements come from `window.checkout.agreementIds` but this variable does not exist ... 

In the Magento code, the agreements are available in this variable `window.checkoutConfig.checkoutAgreements`.

![Capture d’écran du 2024-12-24 10-09-55](https://github.com/user-attachments/assets/87a47fce-c93b-4895-9322-78f9382436d2)

Can you look to fix this bug quickly ? Thank you very much :heart:

**Comment by dimitriBouteille** [comment]
Hi @candemiralp 

I just updated the module to version 2.4.1 and the bug is still. In the Adyen module, the agreements comes from the variable `window.checkout.agreementIds`, except this variable does not exist:(

When I look at the variable `window.checkoutConfig.checkoutAgreements`, I find the agreeements well.

![Capture d’écran du 2024-12-24 11-51-47](https://github.com/user-attachments/assets/c77947c2-9dd7-46b1-88bc-a59199c4c019)

Can you look again to try and fix this bug ? 

![Capture d’écran du 2024-12-24 11-52-59](https://github.com/user-attachments/assets/fc92f576-2d5b-4aaf-89e5-6edf96383d47)

**Comment by candemiralp** [comment]
Hello @dimitriBouteille,

Thanks for reporting it. Let us check again and come back to you.

Best Regards,
Can

**Comment by dimitriBouteille** [comment]
Hi @candemiralp 

Do you have news ?

Best
